{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.backup.enabled }}
  s3-access-key: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.backup.s3.secretKey | b64enc | quote }}
  {{ end }}
{{- end }}
